include:
  - path: ./compose/farming-grants-agreements-ui.yml
    project_directory: .

services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - cdp-tenant

  mock-server:
    image: pactfoundation/pact-stub-server:0.7.0
    profiles:
      - mock
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./src/contracts/consumer/pacts:/app/pacts
    command: ['-p', '8080', '-d', 'pacts']
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
