services:
  farming-grants-agreements-ui:
    build: ./
    ports:
      - '127.0.0.1:3300:3300'
    depends_on:
      redis:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PORT: 3300
      NODE_ENV: ${NODE_ENV:-development}
      REDIS_HOST: ${REDIS_HOST:-redis}
      USE_SINGLE_INSTANCE_CACHE: ${USE_SINGLE_INSTANCE_CACHE:-true}
      BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:3555}
    networks:
      - cdp-tenant